import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { ThemeToggle } from "@/components/theme-toggle";
import { PageTransition } from "@/components/page-transition";

export default function TermsPage() {
  return (
    <PageTransition className="min-h-screen flex items-center justify-center p-4 bg-gradient-to-br from-background via-background to-primary/5 relative">
      <ThemeToggle />
      <div className="w-full max-w-3xl space-y-6">
        <Link href="/login" className="text-sm text-muted-foreground hover:text-primary inline-flex items-center gap-1">
          <ArrowLeft className="h-3 w-3" />
          Back
        </Link>
        <Card>
          <CardHeader>
            <CardTitle className="font-headline text-2xl">Terms of Service</CardTitle>
          </CardHeader>
          <CardContent className="prose dark:prose-invert max-w-none space-y-4 text-sm">
            <p><strong>Last updated:</strong> August 8, 2026</p>

            <h3 className="text-lg font-semibold">1. Acceptance of Terms</h3>
            <p>By accessing and using Study Buddy AI, you agree to be bound by these Terms of Service. If you are accepting these terms on behalf of a school or district, you represent that you have the authority to bind that institution.</p>

            <h3 className="text-lg font-semibold">2. Description of Service</h3>
            <p>Study Buddy AI is an AI-powered educational assistant that provides tutoring, quiz generation, flashcard creation, homework help, and other learning tools. The service uses artificial intelligence models and should be used as a supplementary learning aid.</p>

            <h3 className="text-lg font-semibold">3. User Accounts & Educational Institutions</h3>
            <p>You are responsible for maintaining the confidentiality of your account credentials. For schools and districts, authorized teachers may create classes and invite students. The school acts as the parent's agent and can provide verifiable consent under COPPA for students under 13.</p>

            <h3 className="text-lg font-semibold">4. Acceptable Use</h3>
            <p>You agree not to misuse the service, including but not limited to: attempting to bypass rate limits, sharing accounts, uploading inappropriate content, or using the service to facilitate academic dishonesty (e.g., submitting AI answers directly as your own work). AI guardrails are in place to prevent inappropriate content, but users must still use the platform responsibly.</p>

            <h3 className="text-lg font-semibold">5. AI-Generated Content</h3>
            <p>Content generated by AI models may contain errors. Study Buddy AI does not guarantee the accuracy of AI-generated responses. Always verify important information with authoritative sources, teachers, or textbooks.</p>

            <h3 className="text-lg font-semibold">6. Subscription & Billing</h3>
            <p>Free-tier users have limited monthly token allocations. Pro and Max tier subscriptions provide increased limits and access to additional models. Educational institutions may contact us for bulk or district-wide licensing.</p>

            <h3 className="text-lg font-semibold">7. Termination & Data Deletion</h3>
            <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time from the Profile page. When an account is deleted, all associated educational records and data are permanently purged in compliance with FERPA.</p>

            <h3 className="text-lg font-semibold">8. Changes to Terms</h3>
            <p>We may update these terms from time to time. Continued use of the service constitutes acceptance of the updated terms. Schools and districts will be notified in advance of material changes to our data handling practices.</p>
          </CardContent>
        </Card>
      </div>
    </PageTransition>
  );
}
